version: '3.8'

services:
  wiremock-ui:
    image: wiremock-ui:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: yarn start
    restart: always